<?php 
	$db = array(
		//全局数据库z_all
		'default' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_all',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		//1区game_db和game_db//begin
		'1_game_db' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamedb_1',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		'1_game_log' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamelog_1',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		//1区game_db和game_db//end
		
		//2区game_db和game_db//begin
		'2_game_db' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamedb_2',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		'2_game_log' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamelog_2',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),	
		//3区game_db和game_db//end
		//....
		'3_game_db' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamedb_3',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		'3_game_log' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamelog_3',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		//4区game_db和game_db//end
		//....
		'4_game_db' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamedb_4',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		'4_game_log' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamelog_4',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		//5区game_db和game_db//end
		//....
		'5_game_db' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamedb_5',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
		'5_game_log' => array(
			'hostname' => '172.31.10.32:3306',
			'username' => 'dggame',
			'password' => 'Dh59wQBUiG',
			'database' => 'z_gamelog_5',
			'dbdriver' => 'mysql',
			'dbprefix' => '',
			'pconnect' => FALSE,
			'db_debug' => TRUE,
			'cache_on' => FALSE,
			'cachedir' => '',
			'char_set' => 'utf8',
			'dbcollat' => 'utf8_general_ci',
			'swap_pre' => '',
			'autoinit' => TRUE,
			'stricton' => FALSE
		),
	);
?>